let quests=[],cats=[],campaigns=[],weekly=[],packs=[],stories=[],avatars=[],collectibles=[],current,activeCampaign=null;
const $=s=>document.querySelector(s),base={xp:0,done:[],history:[],streak:0,last:"",best:0,favorites:[],coins:0,name:"",age:6,rewards:[{id:1,name:"Film für den Familienabend auswählen",cost:50},{id:2,name:"Lieblingsdessert auswählen",cost:80}],week:"",weekDone:0,weekClaimed:false,onboarded:false,avatar:"fox",storyProgress:{}};
let state=JSON.parse(localStorage.getItem("qb5")||"null")||{...base};
if(!localStorage.getItem("qb5")){try{let o=JSON.parse(localStorage.getItem("qb4"));if(o)state={...base,...o,onboarded:!!o.name}}catch(e){}}
const save=()=>{localStorage.setItem("qb5",JSON.stringify(state));stats();renderWeekly();renderRewards()},cat=id=>cats.find(x=>x.id===id)||{name:id,emoji:"✦"};
const dayIndex=()=>{let d=new Date(),s=new Date(d.getFullYear(),0,0);return Math.floor((d-s)/86400000)},eligible=()=>quests.filter(q=>q.age<=+state.age);
function choose(list=eligible()){let u=list.filter(q=>!state.done.includes(q.id)),p=u.length?u:list;if(!p.length)p=quests;current=p[Math.floor(Math.random()*p.length)];draw()}
function daily(){let p=eligible();current=p[dayIndex()%p.length];draw()}
function draw(){let c=cat(current.category),f=state.favorites.includes(current.id);$("#questCard").innerHTML=`<div><div class="cardtop"><span class="tag">${c.emoji} ${c.name}</span><button class="heart" id="fav">${f?"♥":"♡"}</button></div><div class="missionno">${activeCampaign?"KAMPAGNEN-MISSION":"MISSION"} ${String(current.id).padStart(2,"0")}</div><h2>${current.title}</h2><p>${current.description}</p></div><div class="meta">⏱ ${current.minutes} Min. · ${current.place==="inside"?"Drinnen":current.place==="outside"?"Draußen":"Überall"} · ab ${current.age} · +${current.xp} XP</div>`;$("#fav").onclick=()=>{let i=state.favorites.indexOf(current.id);i>=0?state.favorites.splice(i,1):state.favorites.push(current.id);save();draw()}}
function wk(){let d=new Date();return d.getFullYear()+"-"+Math.floor(dayIndex()/7)}
function syncWeek(){if(state.week!==wk()){state.week=wk();state.weekDone=0;state.weekClaimed=false}}
function finish(){syncWeek();state.xp+=current.xp;state.coins+=10;if(!state.done.includes(current.id))state.done.push(current.id);state.weekDone++;let t=new Date().toISOString().slice(0,10),y=new Date();y.setDate(y.getDate()-1);if(state.last!==t){state.streak=state.last===y.toISOString().slice(0,10)?state.streak+1:1;state.last=t;state.best=Math.max(state.best,state.streak)}state.history.unshift({id:current.id,title:current.title,date:new Date().toLocaleDateString("de-DE")});$("#earned").textContent=`+${current.xp} XP`;$("#celebrate").classList.add("show");save()}
function renderWeekly(){if(!weekly.length)return;syncWeek();let w=weekly[Math.floor(dayIndex()/7)%weekly.length],n=Math.min(state.weekDone,w.target),done=n>=w.target;if(done&&!state.weekClaimed){state.xp+=w.reward;state.weekClaimed=true;localStorage.setItem("qb5",JSON.stringify(state))}$("#weeklyCard").innerHTML=`<div class="weeklytop"><span>${w.emoji} WOCHEN-CHALLENGE</span><span>${n}/${w.target}</span></div><p>${w.description}${done?` · Bonus +${w.reward} XP ✓`:""}</p><div class="tinybar"><i style="width:${n/w.target*100}%"></i></div>`}
function stats(){let lv=Math.floor(state.xp/100)+1,cur=state.xp%100;$("#streak").textContent=state.streak;$("#levelText").textContent=`Level ${lv}`;$("#xpText").textContent=`${cur} / 100 XP`;$("#xpbar").style.width=cur+"%";$("#bigLevel").textContent=lv;$("#totalXp").textContent=state.xp;$("#doneCount").textContent=state.done.length;$("#bestStreak").textContent=state.best;$("#favCount").textContent=state.favorites.length;$("#childName").value=state.name;$("#childAge").value=state.age;$("#greeting").textContent=state.name?`${state.name}, bereit fürs Abenteuer?`:"Bereit fürs Abenteuer?";$("#profileButton").textContent=state.name?state.name.slice(0,2).toUpperCase():"QB";let b=[["🌱","Erste Mission",state.done.length>=1],["🔥","3er Streak",state.best>=3],["⭐","10 Missionen",state.done.length>=10],["🏆","25 Missionen",state.done.length>=25],["⚡","500 XP",state.xp>=500],["👑","Level 10",lv>=10],["🗺️","3 Abenteuer",campaigns.filter(c=>c.questIds.every(id=>state.done.includes(id))).length>=3],["💚","5 Favoriten",state.favorites.length>=5]];$("#badges").innerHTML=b.map(x=>`<div class="badge ${x[2]?"on":""}"><b>${x[0]}</b><span>${x[1]}</span></div>`).join("");$("#history").innerHTML=state.history.length?state.history.slice(0,10).map(x=>`<div class="historyitem">✓ ${x.title} · ${x.date}</div>`).join(""):"<p class='lead'>Noch keine Mission abgeschlossen.</p>";renderCampaigns();renderCollection();renderStories()}
function renderCampaigns(){$("#campaigns").innerHTML=campaigns.map(c=>{let n=c.questIds.filter(id=>state.done.includes(id)).length,p=n/c.questIds.length*100,z=n===c.questIds.length;return `<div class="campaign ${z?"complete":""}"><div class="top"><div class="emoji">${c.emoji}</div><div><h3>${c.title}</h3><p>${c.description}</p></div></div><div class="bar"><i style="width:${p}%"></i></div><small>${z?"✓ Abenteuer abgeschlossen":`${n}/${c.questIds.length} Missionen`}</small><br><button data-camp="${c.id}">${z?"Nochmal spielen":n?"Fortsetzen":"Starten"}</button></div>`}).join("");document.querySelectorAll("[data-camp]").forEach(b=>b.onclick=()=>startCampaign(b.dataset.camp))}
function startCampaign(id){activeCampaign=campaigns.find(c=>c.id===id);let l=activeCampaign.questIds.map(id=>quests.find(q=>q.id===id)).filter(q=>q&&q.age<=state.age);if(!l.length)return alert("Dieses Abenteuer ist für ein höheres Alter gedacht.");current=l.find(q=>!state.done.includes(q.id))||l[0];draw();show("today")}
function renderPacks(){$("#packs").innerHTML=packs.map(p=>`<button class="pack" data-pack="${p.id}"><b>${p.emoji} ${p.title}</b><small>${p.description}</small></button>`).join("");document.querySelectorAll("[data-pack]").forEach(b=>b.onclick=()=>{let p=packs.find(x=>x.id===b.dataset.pack),f=p.filters,l=eligible().filter(q=>(!f.place||q.place===f.place||q.place==="any")&&(!f.category||q.category===f.category)&&(!f.categories||f.categories.includes(q.category))&&(!f.max||q.minutes<=f.max));activeCampaign=null;choose(l)})}
function renderList(){let a=+$("#age").value||state.age,p=$("#place").value,f=$("#onlyFav").checked,l=quests.filter(q=>q.age<=a&&(p==="all"||q.place===p||q.place==="any")&&(!f||state.favorites.includes(q.id)));$("#questList").innerHTML=l.map(q=>`<div class="quest"><small>${cat(q.category).emoji} ${cat(q.category).name} · ${q.minutes} Min. ${state.done.includes(q.id)?"· ✓":""}</small><h3>${q.title} ${state.favorites.includes(q.id)?"♥":""}</h3><p>${q.description}</p><button data-q="${q.id}">Starten</button></div>`).join("")||"<p class='lead'>Keine passenden Missionen.</p>";document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{activeCampaign=null;current=quests.find(q=>q.id==b.dataset.q);draw();show("today")})}
function renderRewards(){$("#coins").textContent=state.coins;$("#rewardList").innerHTML=state.rewards.map(r=>`<div class="reward"><div><h3>${r.name}</h3><p>${r.cost} ◆</p></div><button data-redeem="${r.id}" ${state.coins<r.cost?"disabled":""}>Einlösen</button></div>`).join("");document.querySelectorAll("[data-redeem]").forEach(b=>b.onclick=()=>{let r=state.rewards.find(x=>x.id==b.dataset.redeem);if(state.coins>=r.cost&&confirm(`„${r.name}“ für ${r.cost} Münzen einlösen?`)){state.coins-=r.cost;save()}})}
function renderStories(){if(!stories.length)return;$("#storyPreview").innerHTML=stories.map(s=>{let n=s.chapters.filter(c=>state.done.includes(c.questId)).length;return `<div class="storytile"><div class="storyemoji">${s.emoji}</div><h3>${s.title}</h3><p>${s.intro}</p><div class="bar"><i style="width:${n/s.chapters.length*100}%"></i></div><small>${n}/${s.chapters.length} Kapitel</small><br><button data-story="${s.id}">${n?"Weiter":"Geschichte starten"}</button></div>`}).join("");document.querySelectorAll("[data-story]").forEach(b=>b.onclick=()=>openStory(b.dataset.story))}
function openStory(id){let s=stories.find(x=>x.id===id),firstLocked=false;$("#storyContent").innerHTML=`<div class="storyhero"><div class="bigemoji">${s.emoji}</div><h2>${s.title}</h2><p>${s.intro}</p></div>`+s.chapters.map((c,i)=>{let done=state.done.includes(c.questId),prev=i===0||state.done.includes(s.chapters[i-1].questId),open=done||prev;return `<div class="chapter ${open?"open":""} ${done?"done":""}"><div class="chapterno">${done?"✓":i+1}</div><div><h3>${c.title}</h3><p>${open?c.text:"Dieses Kapitel ist noch geheim."}</p>${open?`<button data-chapter="${c.questId}">${done?"Nochmal spielen":"Mission starten"}</button>`:""}</div></div>`}).join("");$("#storyScreen").classList.add("show");document.querySelectorAll("[data-chapter]").forEach(b=>b.onclick=()=>{current=quests.find(q=>q.id==b.dataset.chapter);activeCampaign=null;$("#storyScreen").classList.remove("show");draw();show("today")})}
function renderCollection(){if(!avatars.length)return;$("#avatarShelf").innerHTML=avatars.map(a=>{let u=state.done.length>=a.need;return `<div class="collect avatarChoice ${u?"unlocked":""} ${state.avatar===a.id?"selected":""}" data-avatar="${a.id}"><b>${u?a.emoji:"🔒"}</b><span>${a.name}</span><small>${u?"Freigeschaltet":a.need+" Missionen"}</small></div>`}).join("");document.querySelectorAll("[data-avatar]").forEach(x=>x.onclick=()=>{let a=avatars.find(a=>a.id===x.dataset.avatar);if(state.done.length>=a.need){state.avatar=a.id;save();renderCollection()}});$("#collection").innerHTML=collectibles.map(a=>{let u=state.done.length>=a.need;return `<div class="collect ${u?"unlocked":""}"><b>${u?a.emoji:"?"}</b><span>${u?a.name:"Geheim"}</span><small>${u?"Gefunden":a.need+" Missionen"}</small></div>`}).join("");let av=avatars.find(a=>a.id===state.avatar);if(av&&state.done.length>=av.need)$("#profileButton").textContent=av.emoji}
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===id));if(id==="profile")stats();if(id==="adventures")renderList();if(id==="rewards")renderRewards()}
async function init(){[quests,cats,campaigns,weekly,packs,stories,avatars,collectibles]=await Promise.all(["quests","categories","campaigns","weekly","packs","stories","avatars","collectibles"].map(x=>fetch(`data/${x}.json`).then(r=>r.json())));syncWeek();daily();renderList();renderPacks();stats();renderWeekly();renderRewards();if(!state.onboarded)$("#onboarding").classList.add("show");if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js")}
$("#closeStory").onclick=()=>$("#storyScreen").classList.remove("show");$("#done").onclick=finish;$("#next").onclick=()=>{activeCampaign=null;choose()};$("#continue").onclick=()=>{$("#celebrate").classList.remove("show");activeCampaign?startCampaign(activeCampaign.id):choose()};$("#age").onchange=renderList;$("#place").onchange=renderList;$("#onlyFav").onchange=renderList;$("#profileButton").onclick=()=>show("profile");$("#saveProfile").onclick=()=>{state.name=$("#childName").value.trim();state.age=+$("#childAge").value;state.onboarded=true;save();daily()};$("#startQuestbox").onclick=()=>{state.name=$("#onName").value.trim()||"Abenteurer";state.age=+$("#onAge").value;state.onboarded=true;$("#onboarding").classList.remove("show");save();daily()};$("#addReward").onclick=()=>$("#rewardModal").classList.add("show");$("#cancelReward").onclick=()=>$("#rewardModal").classList.remove("show");$("#saveReward").onclick=()=>{let n=$("#rewardName").value.trim(),c=+$("#rewardCost").value;if(n&&c>=10){state.rewards.push({id:Date.now(),name:n,cost:c});$("#rewardModal").classList.remove("show");$("#rewardName").value="";save()}};$("#exportData").onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="questbox-backup.json";a.click()};$("#importData").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);state={...base,...x};save();daily();alert("Fortschritt importiert.")}catch(e){alert("Datei konnte nicht gelesen werden.")}};r.readAsText(f)};$("#reset").onclick=()=>{if(confirm("Fortschritt wirklich löschen?")){state={...base,rewards:[...base.rewards]};save();daily()}};document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.view));init();