
let quests=[],categories=[],current=null;
const S=JSON.parse(localStorage.getItem("questbox")||'{"xp":0,"done":[],"history":[],"lastDate":"","streak":0}');
const $=s=>document.querySelector(s);
const cat=id=>categories.find(c=>c.id===id)||{name:id,emoji:"•"};
function save(){localStorage.setItem("questbox",JSON.stringify(S)); renderStats()}
function pick(list=quests){if(!list.length)return; current=list[Math.floor(Math.random()*list.length)];renderQuest()}
function renderQuest(){let c=cat(current.category);$("#questCard").innerHTML=`<div><span class="tag">${c.emoji} ${c.name}</span><h2>${current.title}</h2><p>${current.description}</p></div><div class="meta">⏱ ${current.minutes} Min. · ${current.place==="inside"?"Drinnen":current.place==="outside"?"Draußen":"Überall"} · +${current.xp} XP</div>`}
function renderStats(){let level=Math.floor(S.xp/100)+1;$("#xp").textContent=S.xp;$("#level").textContent=level;$("#streak").textContent=S.streak;$("#pXp").textContent=S.xp+" XP";$("#pLevel").textContent="Level "+level;$("#pDone").textContent=S.done.length+" Quests geschafft";$("#pStreak").textContent=S.streak+" Tage Streak";$("#history").innerHTML=S.history.length?S.history.slice(0,8).map(x=>`<div>✓ ${x.title}<small> · ${x.date}</small></div>`).join(""):"<p>Noch keine abgeschlossene Quest.</p>"}
function complete(){if(!current)return; S.xp+=current.xp;if(!S.done.includes(current.id))S.done.push(current.id);let today=new Date().toISOString().slice(0,10);if(S.lastDate!==today){let y=new Date();y.setDate(y.getDate()-1);S.streak=S.lastDate===y.toISOString().slice(0,10)?S.streak+1:1;S.lastDate=today}S.history.unshift({title:current.title,date:new Date().toLocaleDateString("de-DE")});save();pick()}
function renderList(){let t=$("#timeFilter").value,p=$("#placeFilter").value;let list=quests.filter(q=>(t==="all"||q.minutes==t)&&(p==="all"||q.place===p||q.place==="any"));$("#questList").innerHTML=list.map(q=>{let c=cat(q.category);return `<div class="quest-item"><small>${c.emoji} ${c.name} · ${q.minutes} Min.</small><h3>${q.title}</h3><p>${q.description}</p><button data-id="${q.id}">Quest starten</button></div>`}).join("");document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{current=quests.find(q=>q.id==b.dataset.id);renderQuest();show("home")})}
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===id));if(id==="progress")renderStats()}
async function init(){[quests,categories]=await Promise.all([fetch("data/quests.json").then(r=>r.json()),fetch("data/categories.json").then(r=>r.json())]);pick();renderList();renderStats();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js")}
$("#done").onclick=complete;$("#next").onclick=()=>pick();$("#surprise").onclick=()=>pick();$("#five").onclick=()=>pick(quests.filter(q=>q.minutes===5));$("#timeFilter").onchange=renderList;$("#placeFilter").onchange=renderList;$("#reset").onclick=()=>{if(confirm("Fortschritt wirklich löschen?")){Object.assign(S,{xp:0,done:[],history:[],lastDate:"",streak:0});save()}};$("#theme").onclick=()=>document.body.classList.toggle("light");document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.view));init().catch(e=>{$("#questCard").innerHTML="<h2>QUESTBOX</h2><p>Bitte über einen Webserver oder GitHub Pages öffnen.</p>"});
