let quests=[],cats=[],campaigns=[],current;
const $=s=>document.querySelector(s), state=JSON.parse(localStorage.getItem("qb2")||'{"xp":0,"done":[],"history":[],"streak":0,"last":"","best":0}');
const save=()=>{localStorage.setItem("qb2",JSON.stringify(state));stats()};
const cat=id=>cats.find(x=>x.id===id)||{name:id,emoji:"✦"};
function choose(list=quests){let unseen=list.filter(q=>!state.done.includes(q.id));let pool=unseen.length?unseen:list;current=pool[Math.floor(Math.random()*pool.length)];draw()}
function draw(){let c=cat(current.category);$("#questCard").innerHTML=`<div><span class="tag">${c.emoji} ${c.name}</span><div class="missionno">MISSION ${String(current.id).padStart(2,"0")}</div><h2>${current.title}</h2><p>${current.description}</p></div><div class="meta">⏱ ${current.minutes} Min. · ${current.place==="inside"?"Drinnen":current.place==="outside"?"Draußen":"Überall"} · ab ${current.age} · +${current.xp} XP</div>`}
function finish(){if(!current)return;state.xp+=current.xp;if(!state.done.includes(current.id))state.done.push(current.id);let t=new Date().toISOString().slice(0,10),y=new Date();y.setDate(y.getDate()-1);let ys=y.toISOString().slice(0,10);if(state.last!==t){state.streak=state.last===ys?state.streak+1:1;state.last=t;state.best=Math.max(state.best,state.streak)}state.history.unshift({title:current.title,date:new Date().toLocaleDateString("de-DE")});$("#earned").textContent=`+${current.xp} XP`;$("#celebrate").classList.add("show");save()}
function stats(){let lv=Math.floor(state.xp/100)+1,cur=state.xp%100;$("#streak").textContent=state.streak;$("#levelText").textContent=`Level ${lv}`;$("#xpText").textContent=`${cur} / 100 XP`;$("#xpbar").style.width=cur+"%";$("#bigLevel").textContent=lv;$("#totalXp").textContent=state.xp;$("#doneCount").textContent=state.done.length;$("#bestStreak").textContent=state.best;$("#rank").textContent=lv>=8?"Quest-Legende":lv>=5?"Abenteurer":lv>=3?"Entdecker":"Neuling";let bd=[["🌱","Erste Mission",state.done.length>=1],["🔥","3er Streak",state.best>=3],["⭐","10 Missionen",state.done.length>=10],["🏆","25 Missionen",state.done.length>=25],["⚡","500 XP",state.xp>=500],["👑","Level 10",lv>=10]];$("#badges").innerHTML=bd.map(x=>`<div class="badge ${x[2]?"on":""}"><b>${x[0]}</b><span>${x[1]}</span></div>`).join("");$("#history").innerHTML=state.history.length?state.history.slice(0,8).map(x=>`<div class="historyitem">✓ ${x.title} · ${x.date}</div>`).join(""):"<p class='lead'>Noch keine Mission abgeschlossen.</p>";renderCampaigns()}
function renderCampaigns(){if(!campaigns.length)return;$("#campaigns").innerHTML=campaigns.map(c=>{let n=c.questIds.filter(id=>state.done.includes(id)).length,p=n/c.questIds.length*100;return `<div class="campaign"><div class="top"><div class="emoji">${c.emoji}</div><div><h3>${c.title}</h3><p>${c.description}</p></div></div><div class="bar"><i style="width:${p}%"></i></div><small>${n} / ${c.questIds.length} Missionen geschafft</small><br><button data-camp="${c.id}">${n? "Fortsetzen":"Abenteuer starten"}</button></div>`}).join("");document.querySelectorAll("[data-camp]").forEach(b=>b.onclick=()=>{let c=campaigns.find(x=>x.id===b.dataset.camp),list=c.questIds.map(id=>quests.find(q=>q.id===id));choose(list);show("today")})}
function renderList(){let a=+$("#age").value,p=$("#place").value,list=quests.filter(q=>(!a||q.age<=a)&&(p==="all"||q.place===p||q.place==="any"));$("#questList").innerHTML=list.map(q=>`<div class="quest"><small>${cat(q.category).emoji} ${cat(q.category).name} · ${q.minutes} Min.</small><h3>${q.title}</h3><p>${q.description}</p><button data-q="${q.id}">Starten</button></div>`).join("");document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{current=quests.find(q=>q.id==b.dataset.q);draw();show("today")})}
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===id));if(id==="profile")stats()}
async function init(){[quests,cats,campaigns]=await Promise.all(["quests","categories","campaigns"].map(x=>fetch(`data/${x}.json`).then(r=>r.json())));choose();renderList();stats();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js")}
$("#done").onclick=finish;$("#next").onclick=()=>choose();$("#continue").onclick=()=>{$("#celebrate").classList.remove("show");choose()};$("#age").onchange=renderList;$("#place").onchange=renderList;$("#reset").onclick=()=>{if(confirm("Fortschritt wirklich löschen?")){Object.assign(state,{xp:0,done:[],history:[],streak:0,last:"",best:0});save();choose()}};document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.view));init();